#ifndef TETRIS_HPP
#define TETRIS_HPP

#define TETRIS_BOARD_WIDTH 10
#define TETRIS_BOARD_HEIGHT 18

#define TETRIS_TILE_SIZE 18
#define TETRIS_FIELD_LEFT 60
#define TETRIS_FIELD_BOTTOM 320
#define TETRIS_GAMEOVER_ROW 14

#endif // TETRIS_HPP
